server {
	listen 80;
	server_name _;

	root /srv;
	index index.html;

	gzip on;
	gzip_vary on;
	gzip_types text/css application/javascript application/json image/svg+xml application/xml text/xml;

	location / {
		try_files $uri $uri.html $uri/ =404;
	}
}
